# Useage: conda env create -f environment.yml
name: bhml
channels:
  - nbsantos
dependencies:
  - python=2.7
  - jupyter
  - pandas
  - tensorflow-gpu
  - scipy
  - scikit-learn
  - matplotlib
  - statsmodels
  - seaborn
  - pillow
  - textblob
  - keras-gpu
